# Introdução ao `numpy`

In [ ]:
import numpy as np
import matplotlib.pyplot as plt  # Biblioteca para gerar gráficos

Vamos criar umas matrizes e vetores para começar...

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\ &
\boldsymbol{B} &= \begin{bmatrix}1 & 3\\ 5 & 7\end{bmatrix}\\\\
\boldsymbol{v}_1 &= \begin{bmatrix}5 & 3\end{bmatrix}\ &
\boldsymbol{v}_2 &= \begin{bmatrix}9 & 2 & 1\end{bmatrix}
\end{aligned}$$

In [ ]:
A = np.array([[2,0],
              [4,6],
              [8,2]]) # Matriz A

B = np.array([[1,3],
              [5,7]]) # Matriz B

v1 = np.array([5,3])  # Vetor 1

v2 = np.array([9,2,1])# Vetor 2

print("Matriz A")
print (A)

print("Matriz B")
print (B)

print("Vetor 1")
print (v1)

print("Vetor 2")
print (v2)

Matriz A
[[2 0]
 [4 6]
 [8 2]]
Matriz B
[[1 3]
 [5 7]]
Vetor 1
[5 3]
Vetor 2
[9 2 1]


**shape()** - mostra a forma do array, ajuda a encontrar as dimensões.

In [ ]:
print("Dimensão de A:", A.shape)
print("Dimensão de B:", B.shape)
print("Dimensão de v1:", v1.shape)
print("Dimensão de v2:", v1.shape)

Dimensão de A: (3, 2)
Dimensão de B: (2, 2)
Dimensão de v1: (2,)
Dimensão de v2: (2,)


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\boldsymbol{A}^{\top} &= \begin{bmatrix}2 & 4 & 8\\ 0 & 6 & 2\end{bmatrix}
\end{aligned}$$

In [ ]:
print("Matriz original:")
print(A)
print("Matriz transposta:")
print(A.T)

Matriz original:
[[2 0]
 [4 6]
 [8 2]]
Matriz transposta:
[[2 4 8]
 [0 6 2]]


$$\begin{aligned}
\boldsymbol{A}[0] &= \begin{bmatrix}2 & 0\end{bmatrix}\\
\boldsymbol{A}[[0,2]] &= \begin{bmatrix}2 & 0\\ 8 & 2\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print("Primeira linha de A:")
print(A[0], "dimensão:", A[0].shape) # Primeira linha de A
print("Primeira e terceira linha de A:")
print(A[[0,2]], "dimensão:", A[[0,2]].shape) # Primeira e terceira linha de A
print("Primeira linha de A (mantendo 2 dimensões):")
print(A[[0]], "dimensão:", A[[0]].shape) # Primeira linha de A (mantendo 2 dimensões)

Primeira linha de A:
[2 0] dimensão: (2,)
Primeira e terceira linha de A:
[[2 0]
 [8 2]] dimensão: (2, 2)
Primeira linha de A (mantendo 2 dimensões):
[[2 0]] dimensão: (1, 2)


$$\begin{aligned}
\boldsymbol{A}[:,0] &= \begin{bmatrix}2 & 4 & 8\end{bmatrix}\\
\boldsymbol{A}[:,[0]] &= \begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}
\end{aligned}$$

In [ ]:
print("Primeira coluna do A:")
print(A[:,0], "dimensão:", A[:,0].shape) # Primeira coluna do A
print("Primeira e segunda coluna do A:")
print(A[:,[0,1]], "dimensão:", A[:,[0,1]].shape) # Primeira e segunda coluna do A
print("Primeira coluna do A (mantendo 2 dimensões):")
print(A[:,[0]], "dimensão:", A[:,[0]].shape) # Primeira coluna do A (mantendo 2 dimensões)

Primeira coluna do A:
[2 4 8] dimensão: (3,)
Primeira e segunda coluna do A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Primeira coluna do A (mantendo 2 dimensões):
[[2]
 [4]
 [8]] dimensão: (3, 1)


$$\begin{aligned}
\left[\begin{bmatrix}2 & 4 & 8\end{bmatrix}; \begin{bmatrix}1 & 2 & 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 4 & 8\\1 & 2 & 3\end{bmatrix}\\
\left[\begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}, \begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 1 \\ 4 & 2 \\ 8 & 3\end{bmatrix}
\end{aligned}$$

**reshape()** - O conceito é muito simples. Vamos tomar a matriz e tentar remodelá-la. Lembre-se que a nova matriz (reformulada) tem de ser compatível com a matriz original. Por exemplo, matrizA tem a forma (4,4); são 16 elementos na matriz, então a nova matriz tem que ter esse número de elementos. Neste a matriz reformulado tem que ter os mesmos 16 elementos independentemente do numeros de colunas ou de linhas. Ex: MatrizA: 4x4 ---> Matriz Reformulada pode ser : 2x8, 8x2, 1x16...

(-1) Significa simplesmente que é uma dimensão desconhecida e queremos que o numpy descubra. E o numpy descobrirá isso observando o 'comprimento da matriz e as dimensões restantes' e certificando-se de que satisfaça os critérios.
Ex: a = np.array([5, 4, 8]
                 [1, 2, 3])
    a.shape (2,3)

    remodelando com (-1) temos:
    a.reshape (-1)
    array([1,2,3,4,5,8]) ---> compativel com a forma original(2,3)

r_[] - Mescla Linhas - Concatena

In [ ]:
a = np.array([2, 4, 8]).reshape((1,-1))
b = np.array([1, 2, 3]).reshape((1,-1))
ab = np.r_[a,b]

print(a, "dimensão:", a.shape)
print(b, "dimensão:", b.shape)
print(ab, "dimensão:", ab.shape) # row stack

[[2 4 8]] dimensão: (1, 3)
[[1 2 3]] dimensão: (1, 3)
[[2 4 8]
 [1 2 3]] dimensão: (2, 3)


In [ ]:
c = np.array([2, 4, 8]).reshape((-1,1))
d = np.array([1, 2, 3]).reshape((-1,1))
cd = np.c_[c,d]

print(c, "dimensão:", c.shape)
print(d, "dimensão:", d.shape)
print(cd, "dimensão:", cd.shape) # column stack

[[2]
 [4]
 [8]] dimensão: (3, 1)
[[1]
 [2]
 [3]] dimensão: (3, 1)
[[2 1]
 [4 2]
 [8 3]] dimensão: (3, 2)


## Matrizes notáveis

$$\begin{aligned}
\boldsymbol{I}_n = \mathtt{np.eye(n)} &= \begin{bmatrix}1 & 0 & \ldots\\ 0 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 1\end{bmatrix}&
\boldsymbol{0}_{n,m} = \mathtt{np.zeros((n,m))} &= \begin{bmatrix}0 & 0 & \ldots\\ 0 & 0 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 0\end{bmatrix}\\
\boldsymbol{1}_{n,m} = \mathtt{np.ones((n,m))} &= \begin{bmatrix}1 & 1 & \ldots\\ 1 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 1 & \ldots & 1\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print("Matriz identidade de ordem 5:")
print(np.eye(5))
print("Matriz de zeros 5x3:")
print(np.zeros((5,3)))
print("Matriz de uns 3x1:")
print(np.ones((3,1)))

Matriz identidade de ordem 5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Matriz de zeros 5x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de uns 3x1:
[[1.]
 [1.]
 [1.]]


Além dessas matrizes notáveis, também podemos fazer matrizes aleatórias:

`np.random.rand(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.rand(n,m)}]_{ij} \sim \mathcal{U}(0,1)$.

Ou seja, $[\mathtt{np.random.rand(n,m)}]_{ij} \in [0,1)$

`np.random.randn(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.randn(n,m)}]_{ij} \sim \mathcal{N}(0,1)$

Ou seja, $[\mathtt{np.random.randn(n,m)}]_{ij} \in (-\infty,+\infty)$

In [ ]:
print("Matriz 5x3 de números aleatórios amostrados de U(0,1):")
print(np.random.rand(5,3))
print("Matriz 2x2 de números aleatórios amostrados de N(0,1):")
print(np.random.randn(2,2))

Matriz 5x3 de números aleatórios amostrados de U(0,1):
[[0.79568737 0.78509395 0.72057672]
 [0.50883488 0.31392266 0.0128344 ]
 [0.99466598 0.98294818 0.50975356]
 [0.15002207 0.53872309 0.01146569]
 [0.02205521 0.71496149 0.72549985]]
Matriz 2x2 de números aleatórios amostrados de N(0,1):
[[-0.44051846  1.2028409 ]
 [-0.15675663 -0.74684512]]


## Operações lineares

Produto de escalares por matrizes:
$$\begin{aligned}
5\boldsymbol{A} &= \begin{bmatrix}2\cdot 5 & 0\cdot 5\\ 4\cdot 5 & 6\cdot 5\\ 8\cdot 5 & 2\cdot 5\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}10 & 0\\ 20 & 30\\ 40 & 10\end{bmatrix}
\end{aligned}$$

In [ ]:
print(5 * A)

[[10  0]
 [20 30]
 [40 10]]


Soma de matrizes:
$$\begin{aligned}
\boldsymbol{A}+\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}4 & 0\\ 8 & 12\\ 26 & 4\end{bmatrix}
\end{aligned}$$

In [ ]:
print(A + A)

[[ 4  0]
 [ 8 12]
 [16  4]]


Produto com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \bullet \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\bullet\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5\cdot 2 & 3\cdot 0\\ 5\cdot 4 & 3\cdot 6\\ 5\cdot 8 & 3\cdot 2\end{bmatrix}\\
&= \begin{bmatrix}10 & 0\\ 20 & 18\\ 40 & 6\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print(v1 * A)

[[10  0]
 [20 18]
 [40  6]]


Soma com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \oplus \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\oplus\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5 & 3\\ 5 & 3\\ 5 & 3\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
&= \begin{bmatrix}7 & 3\\ 9 & 9\\ 13 & 5\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print(v1 + A)

[[ 7  3]
 [ 9  9]
 [13  5]]


Cuidado com as dimensões das variáveis:

In [ ]:
print("Vetor v2:")
print(v2, "dimensão:", v2.shape)
print("Matriz A:")
print(A, "dimensão:", A.shape)
try:
    v2 + A
except Exception as e:
    print(e)

Vetor v2:
[9 2 1] dimensão: (3,)
Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
operands could not be broadcast together with shapes (3,) (3,2) 


In [ ]:
print("Matriz A:")
print(A, "dimensão:", A.shape)
print("Matriz B:")
print(B, "dimensão:", B.shape)
try:
    A + B
except Exception as e:
    print(e)

Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Matriz B:
[[1 3]
 [5 7]] dimensão: (2, 2)
operands could not be broadcast together with shapes (3,2) (2,2) 


## Operações não-lineares

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{A ** 2} &= \begin{bmatrix}2^2 & 0^2\\ 4^2 & 6^2\\ 8^2 & 2^2\end{bmatrix}
\end{aligned}$$

In [ ]:
print(A ** 2)

[[ 4  0]
 [16 36]
 [64  4]]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.sqrt(A)} &= \begin{bmatrix}\sqrt{2} & \sqrt{0}\\ \sqrt{4} & \sqrt{6}\\ \sqrt{8} & \sqrt{2}\end{bmatrix}\\
\mathtt{A ** 0.5} &= \begin{bmatrix}2^\frac{1}{2} & 0^\frac{1}{2}\\ 4^\frac{1}{2} & 6^\frac{1}{2}\\ 8^\frac{1}{2} & 2^\frac{1}{2}\end{bmatrix}
\end{aligned}$$

In [ ]:
print("Raiz Quadrada da Matriz A")
print(np.sqrt(A))
print("Matriz A elevada a potencia de 0.5 = Raiz Quadrada da Matriz A")
print(A ** 0.5)

Raiz Quadrada da Matriz A
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]
Matriz A elevada a potencia de 0.5 = Raiz Quadrada da Matriz A
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]


## Operações de agregação

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A)} &= \frac{2 + 0 + 4 + 6 + 8 + 2}{2\cdot 3}\\
\mathtt{np.sum(A)} &= 2 + 0 + 4 + 6 + 8 + 2\\
\mathtt{np.prod(A)} &= 2 \cdot 0 \cdot 4 \cdot 6 \cdot 8 \cdot 2\\
\end{aligned}$$

mean() - Média

sum() - Soma

prod() - Multiplicação

In [ ]:
np.mean(A), np.sum(A), np.prod(A)

(3.6666666666666665, 22, 0)

In [ ]:
A.mean(), A.sum(), A.prod()

(3.6666666666666665, 22, 0)

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=0)} &= \frac{1}{3}\begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=0)} &= \begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=0)} &= \begin{bmatrix}2 \cdot 4 \cdot 8 & 0 \cdot 6 \cdot 2\end{bmatrix}\\
\end{aligned}$$

axis=0 >>> Linhas

axis=1 >>> Colunas

In [ ]:
np.mean(A, axis=0), np.sum(A, axis=0), np.prod(A, axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

In [ ]:
A.mean(axis=0), A.sum(axis=0), A.prod(axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=1)} &= \frac{1}{2}\begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=1)} &= \begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=1)} &= \begin{bmatrix}2 \cdot 0 & 4 \cdot 6 & 8 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [ ]:
np.mean(A, axis=1), np.sum(A, axis=1), np.prod(A, axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [ ]:
A.mean(axis=1), A.sum(axis=1), A.prod(axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [ ]:
np.mean(A, axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [ ]:
A.mean(axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [ ]:
A - A.mean(axis=0, keepdims=True)

array([[-2.66666667, -2.66666667],
       [-0.66666667,  3.33333333],
       [ 3.33333333, -0.66666667]])

## Multiplicação de Matrizes

Para matrizes $\boldsymbol{X} \in \mathbb{R}^{a\times b}$ e $\boldsymbol{Y} \in \mathbb{R}^{b\times c}$, temos que
$\boldsymbol{XY} \in \mathbb{R}^{a\times c}$. No Numpy, essa operação é representada por $\texttt{X @ Y}$.

A multiplicação é definida por:
$$\begin{aligned}
(\boldsymbol{XY})_{ij} = \sum_k \boldsymbol{X}_{ik}\boldsymbol{Y}_{kj}
\end{aligned}$$

In [ ]:
print(A @ B)
print("Dimensão de A @ B:", (A@B).shape)

[[ 2  6]
 [34 54]
 [18 38]]
Dimensão de A @ B: (3, 2)


Cuidado com as dimensões das matrizes:

In [ ]:
try:
    B @ A
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [ ]:
print(A @ B @ v1)
print((A @ B) @ v1)

[ 28 332 204]
[ 28 332 204]


### Inversão de matrizes
Outra operação bastante comum é multiplicar uma matriz pela inversa dela...

Seja $\boldsymbol{B}$ uma matriz inversível, então $\boldsymbol{B}^{-1} \boldsymbol{B} = \boldsymbol{I}$


In [ ]:
print(B)

[[1 3]
 [5 7]]


**linalg.inv(a)**

Calcula o inverso (multiplicativo) de uma matriz.

In [ ]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [ ]:
print(B_inv @ B)

[[1. 0.]
 [0. 1.]]


A inversa pode ser usada no produto com vetores:
$\boldsymbol{B}^{-1} \boldsymbol{v}_1$

In [ ]:
print(B_inv @ v1)

[-3.25  2.75]


Porém, existe uma outra forma mais eficiente de computar a mesma coisa:

Se $\boldsymbol{B}^{-1} \boldsymbol{v}_1 = \boldsymbol{x}$, então $\boldsymbol{B} \boldsymbol{x} = \boldsymbol{v}_1$.
Ou seja, estamos resolvendo o sistema de equações lineares com coeficientes $\boldsymbol{B}$ e resultado $\boldsymbol{v}_1$


**linalg.solve(a, b)**

Resolve uma equação matricial linear ou sistema de equações escalares lineares.

In [ ]:
print(np.linalg.solve(B,v1))

[-3.25  2.75]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Leitura de arquivos com dados

Normalmente os dados na disciplina serão recebidos no formato CSV. Isso significa que o dado é estruturado da seguinte maneira:
```
idade,pressão_sanguínea # Um cabeçalho opcional
39,144 # Dados separados por vírgulas ou outro separador
47,220
....
```

In [ ]:
peixe_dataset = np.genfromtxt('/content/drive/MyDrive/Data/peixes.txt', delimiter=',', skip_header=1)
peixe_dataset